### PR TITLE
A bit of polish

### PR DESCRIPTION
**Pull request by zibetnu**
After my initial dismay when I found that hook drift was not actually fixed, I got a carried away with some refactoring. I'm pretty happy with the results! Most notably:
- Hook drift is _actually_ fixed this time around
- Better pause/unpause handling
- Less stuttering
- Better fullscreen toggling

### CODE REVIEW

**Comment by rilifon** [comment]
Wow, that's a heafty PR hahahha

I took a look on the overall changes, but I don't think I'll be able to make a proper and extensive testing on your code. But since we've already changed some discussions in the past, I'm taking a leap of faith and merging this with the base repo, you let me know if somethings ends up broken, and in any case we can just revert the changes.

**Comment by rilifon** [comment]
Something that I've noticed, but it seems a few shaders (the ones that create the waves around floating objects) are not working as intended (could be the difference between Godot versions, I think I've came across something similar in another project)

But since its such a minor detail, I think we can keep the changes for now. Also, I'll try my best to push this version to Steam today!

**Comment by zibetnu** [comment]
Oh snap, I don't know how I missed that shader problem. I'll look into fixing that asap. In the meantime, thank you for merging this PR so promptly.

**Comment by zibetnu** [comment]
I didn't notice the shader issue because I didn't test regenerating the .import folder after it was deleted. I'm attempting to figure out why regenerating the .import folder removes the resource paths for the distortion and noise images from the .tres files of the affected shaders.

**Pull request merged**
