### PR TITLE
Use Direct movement instead of Tank movement

### PR DESCRIPTION
**Pull request by zibetnu**
Most people find Direct movement more intuitive than Tank movement, so I believe it should be used instead of Tank movement.

This change also fixes what I call "hook drift," where a player's hook sprite rotates as their shark turns even if the player is still aiming in the same direction.

### CODE REVIEW

**Comment by rilifon** [comment]
Hey there, thanks for the PR!

The default choice of Tank movement (solely for keyboard players, since if I recall correctly, players using gamepad controls have the  "Direct" movement as default) was a deliberate choice.
After considerate amount of playtesting with different groups, althought initially the tank movement felt more "difficult to pick up", after a few sessions we notice a lot more positive feedback from using it, hence the design choice to make it the default.

I did once wanted the game to have an in-game option to toggle your prefered method for each player port, but due to limited time of development, and since we have already stop developing the game for a few years now, I've never managed to actually implement this, nor have plans to make it for the time being.

If you'd like to implement such a feature, as in **still leaving the default control scheme for keyboard as Tank but allowing players to manually choose their prefered control scheme in the character select screen**, I'll happilly review your PR and merge it if it turns out to be properly implemented, albeit it would be a more complicated task than what you've made so far.

Nevertheless, I again thank you for taking the time in playing our game and making this PR, I'm glad people still have some fun with Hooksharks even to this day, I have fond memories of "wasting" a few hours shooting hooks at my friebds while riding giant sharks :)

**Comment by zibetnu** [comment]
Thanks for taking the time to look at this! I'll look into making the movement type something that players can select.

Also, both keyboard and gamepad players have tank movement in the current version of the game. I guess that was unintended?

**Comment by zibetnu** [comment]
Here's my implementation! It adds the following:

- gamepads now default to direct movement instead of tank movement
- keyboard still defaults to tank movement
- players can choose either movement type on the character selection screen

**Comment by zibetnu** [comment]
Also, what would it take for these changes to get pushed to Steam? If that's not an option at this point, then are there any restrictions I should be aware of if I wanted to put my own version on Steam?

**Comment by rilifon** [comment]
Nice changes! I'll be reviewing them next week (I'm still on vacation 😅). And if the changes seem good, I'll push them to the Steam version no problem!

**Comment by zibetnu** [comment]
(Please don't bother with this until you're back from vacation; I don't want to distract from that.)

I'm toying with the idea of adding stuff like a few new maps and maybe a new item. If I go ahead with that, would you rather I kept that in my own repository or made PRs for that stuff? This is the first time I've contributed to an open source project, so I apologize if this is a silly question.

**Comment by rilifon** [comment]
Hey there! I'm back from my vacation, I'll try to review your stuff this week!

Feel free to keep sending PR's, I'll love to see them, and it's the best way to contribute directly to the game. Any good stuff I'll be sure to put in the game. We can talk more directly through Discord too if you'd like.

Thanks for taking an interest in Hooksharks, and I'll get back with comments or merge it all together as soon as I can :)

**Comment by rilifon** [comment]
Seems great, liked the new outlines too. I'll try to push it to Steam version by the end of this week

**Pull request merged**
